### PR TITLE
Add crowd_pay to spec_helper

### PR DESCRIPTION
**Pull request by rlqualls**
Small commit, but lots of different things are breaking the tests right now, so I'm keeping things simple.

### CODE REVIEW

**Comment by kmanzana** [comment]
@rlqualls how did you find out about this project?  I thought you were someone else from Qwinix but I noticed you are not.  Are you affiliated at all?

**Comment by rlqualls** [comment]
@kmanzana I'm not affiliated. I just came across it when googling for pull requests.

**Comment by kmanzana** [comment]
@rlqualls nice. Well thanks for the help. Sorry that it was kind of half baked.  Working now but still need to set up Travis and publish to RubyGems. How does one google for pull requests?

**Comment by rlqualls** [comment]
@kmanzana For example, "rails consulting colorado" has qwinix on page 4. Maybe that's where I found it. Once I find a company, I search "github <that company>" to see if they have an account and if there's anything to work on.

**Pull request merged**
