### PR TITLE
Move all gem requirements to gemspec

### PR DESCRIPTION
**Pull request by h0lyalg0rithm**

### CODE REVIEW

**Comment by kmanzana** [comment]
I'm assuming that it's better practice to have the dev dependencies in the gemspec instead of just in gemfile?  I'm fine with doing this.  Would you mind merging in master and then I can merge the PR?

**Comment by h0lyalg0rithm** [comment]
@kmanzana I have seen many libs do the same.I usually follow the same in my libraries.

**Comment by h0lyalg0rithm** [comment]
I have rebased my code Please merge

**Comment by kmanzana** [comment]
thanks!

**Pull request merged**
